name = "Petal SMP"
author = "macuguita, dayasaur"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f99576f1934fa9515d0459b58e5340429d51f9429e950acf2cef014dcac4df35"

[versions]
fabric = "0.18.2"
minecraft = "1.21.1"
