name = "Petal SMP"
author = "macuguita, dayasaur"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db8258308b1e8f43b5f2516e9e17e7e68fd7dc6a6fbc7a931f1488544fe46d50"

[versions]
fabric = "0.18.2"
minecraft = "1.21.1"
