name = "Petal SMP"
author = "macuguita, dayasaur"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b90fd2d359bffad0de4fd1f306ecbf675b87d07c36a0f30afbf0db27ed6ade34"

[versions]
fabric = "0.18.2"
minecraft = "1.21.1"
